# Generated by Django 4.1.7 on 2023-03-12 13:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('content', models.TextField(max_length=2000)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('Category', models.CharField(max_length=100)),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
