# Generated by Django 4.1.7 on 2023-03-18 03:12

import Blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_blog_date_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CategoryName', models.CharField(max_length=40)),
                ('CategoryImage', models.ImageField(upload_to=Blog.models.imgsave)),
                ('CategoryDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
