# Generated by Django 4.1.7 on 2023-03-18 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blog.category'),
        ),
    ]
