# Generated by Django 4.1.7 on 2023-03-18 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_blog_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='Category',
            new_name='category',
        ),
    ]
