# Generated by Django 4.1.7 on 2023-03-18 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0006_rename_category_blog_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='c',
            new_name='blog_id',
        ),
    ]
