# Generated by Django 4.1.7 on 2023-03-22 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0007_rename_c_comments_blog_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='comment_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
